### ISSUE TITLE
厉害了，一堆C#8，没法用啊，也就个人项目玩玩了

### ISSUE THREAD

**Issue by icetech233** [walterlv/Walterlv.Packages#1]

**Comment by walterlv** [comment]
C# 8 开起来还是很随意的，也强烈建议在产品项目中开启。对开发非常友好，也不影响用户那边的产品的。

不过，如果你们项目用的是旧版本的 VS，可以通过这种方式开启：
- [使用 Microsoft.Net.Compilers 在旧版本的 Visual Studio 2013/2015/2017 中开启新的 C# 7.x 和 C# 8 语法 - walterlv](https://blog.walterlv.com/post/add-lastest-csharp-support-for-old-visual-studio.html)
