### ISSUE TITLE
WindowAccentCompositor系统环境识别错误以及亚克力效果运行不正常

### ISSUE THREAD

**Issue by skies-unbound** [walterlv/Walterlv.Packages#15]
AccentState.ACCENT_ENABLE_BLURBEHIND 有效，可以正常使窗口透明
AccentState.ACCENT_ENABLE_ACRYLICBLURBEHIND 同有效，但拖动窗口时会极其缓慢，缩放窗口没有影响
录制了一个拖动的问题

[bandicam 2020-08-20 09-24-07-486_x264.zip](https://github.com/walterlv/Walterlv.Packages/files/5100134/bandicam.2020-08-20.09-24-07-486_x264.zip)

**Comment by unboundskies** [comment]
问题为系统绘制产生，此API只能用来绘制 Taskbar, Start Menu 等固定窗口。存在与常规窗体的不兼容，慎用此API
