### ISSUE TITLE
win11中、亚克力透明效果失效

### ISSUE THREAD

**Issue by NeverMorewd** [walterlv/Walterlv.Packages#35]

**Comment by NeverMorewd** [comment]
好用、、把注释掉的代码放开就好了。之前用过一个fluentUI wpf的代码、win10好用、但是win11失效。实现原理区别也很大，那个是用了一张图片做的毛玻璃效果。

**Comment by walterlv** [comment]
> 好用、、把注释掉的代码放开就好了。之前用过一个fluentUI wpf的代码、win10好用、但是win11失效。实现原理区别也很大，那个是用了一张图片做的毛玻璃效果。

微软还没有完全在 Win32 里面放开，之前能用有点钻空子。
